GET https://cors-anywhere.herokuapp.com/https://support.infocaption.com/API/lucene/guidesearch?searchQuery=färg&page=$1

###

GET https://support.infocaption.com/API/lucene/guidesearch?searchQuery=färg&page=$1